/* Build products_history.js — the committed product-by-day grid the Products
   page draws before its live top-up arrives.
   Run: node source/build_products_history.js <grid.json> [<grid.json> ...]

   Each input is a /api/shopify?dataset=productsHistory payload (pull the range
   in halves if one call would run past the route's 60s). Later files win where
   days overlap. Today's partial day is dropped: a committed file must hold
   only complete days, and the page's 45-day live pull covers the tail. */
const fs = require('fs'), path = require('path');
const files = process.argv.slice(2);
if (!files.length) { console.error('usage: node source/build_products_history.js <grid.json> ...'); process.exit(2); }
const parts = files.map(f => JSON.parse(fs.readFileSync(f, 'utf8')));
const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Australia/Brisbane', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());

const daySet = new Set(); parts.forEach(p => p.days.forEach(d => { if (d < today) daySet.add(d); }));
const days = [...daySet].sort(); const di = Object.fromEntries(days.map((d, i) => [d, i]));
const prod = {}; const totals = days.map(() => [0, 0, 0]);
parts.forEach(p => {
  p.products.forEach(pr => {
    const row = prod[pr.title] || (prod[pr.title] = { title: pr.title, k: pr.k, cells: days.map(() => [0, 0, 0]) });
    pr.cells.forEach((c, i) => { const j = di[p.days[i]]; if (j != null) row.cells[j] = c; });
  });
  p.totals.forEach((c, i) => { const j = di[p.days[i]]; if (j != null) totals[j] = c; });
});
const products = Object.values(prod).sort((a, b) => b.cells.reduce((x, c) => x + c[0], 0) - a.cells.reduce((x, c) => x + c[0], 0));
const keys = Object.assign({}, ...parts.map(p => (p.meta && p.meta.keys) || {}));
const out = {
  meta: { source: 'Shopify · ShopifyQL sales, product_title × day', currency: 'AUD',
    builtOn: today, since: days[0], until: days[days.length - 1], days: days.length, products: products.length, keys,
    cells: 'per product, per day: [net_sales, orders containing it, units]; totals: [net_sales, orders, units] for the whole store',
    note: 'Committed snapshot. The Products page replaces the last 45 days live from /api/shopify?dataset=productsRecent. ' +
          'Regenerate: pull ?dataset=productsHistory (in halves) and run source/build_products_history.js.' },
  days, products, totals,
};
const js = `// Product-by-day grid from Shopify (ShopifyQL sales). Generated by source/build_products_history.js on ${today}. Do not hand-edit.\n` +
           `// ${days.length} days ${days[0]} → ${days[days.length - 1]}, ${products.length} products. Cells: [net_sales, orders containing, units].\n` +
           `window.DL_PRODUCTS_HISTORY = ${JSON.stringify(out)};\n`;
fs.writeFileSync(path.join(__dirname, '..', 'products_history.js'), js);
console.log(`products_history.js: ${days.length} days ${days[0]} → ${days[days.length - 1]}, ${products.length} products, ${(js.length / 1024).toFixed(0)} KB`);
